/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAlbumIcon: typeof import('./components/AddAlbumIcon.vue')['default']
    AddMomentIcon: typeof import('./components/AddMomentIcon.vue')['default']
    AlbumItem: typeof import('./components/AlbumItem.vue')['default']
    AlbumsBox: typeof import('./components/AlbumsBox.vue')['default']
    Charts: typeof import('./components/Charts.vue')['default']
    Content: typeof import('./components/Content.vue')['default']
    EmptyStatus: typeof import('./components/EmptyStatus.vue')['default']
    ImageItem: typeof import('./components/ImageItem.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview.vue')['default']
    ImagesBox: typeof import('./components/ImagesBox.vue')['default']
    MomentCard: typeof import('./components/MomentCard.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutSticky: typeof import('nutui-uniapp/components/sticky/sticky.vue')['default']
    NutTabbar: typeof import('nutui-uniapp/components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('nutui-uniapp/components/tabbaritem/tabbaritem.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    Tabbar: typeof import('./components/Tabbar.vue')['default']
    UploadImage: typeof import('./components/UploadImage.vue')['default']
  }
}
