/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
  }
}
