/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/index" |
       "pages/album" |
       "pages/find" |
       "pages/user" |
       "pages/child/addAlbum" |
       "pages/child/addMoment" |
       "pages/child/albumDetail" |
       "pages/child/searchResult" |
       "pages/child/setting";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "pages/index" | "pages/album" | "pages/find" | "pages/user"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
